[platformio]
src_dir = main

[env:esp32s3_n8r8]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 115200
board_build.esp-idf.sdkconfig_path = sdkconfig

; Konfiguracja sprzętowa dla N8R8
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_upload.flash_size = 8MB
board_build.flash_mode = qio

build_flags =
    -DCONFIG_HTTPD_WS_SUPPORT=1

